### ISSUE TITLE
[Feature Request] Output lighting event data

### ISSUE THREAD

**Issue by megalon** [opl-/beatsaber-http-status#1]
Output the data of each of the lighting events, such as the 

- background colors
- laser colors
- laser rotation speed 
- ring rotation speed 
- etc

It could be interesting to sync these lighting events to elements within the overlay.

**Comment by opl-** [comment]
I was planning on adding that already, but had other things to take care of. I'll add it when I have some spare time.

**Comment by opl-** [comment]
This is now a feature as of v1.2.0. Description of the event is provided in protocol.md.
