### ISSUE TITLE
Completely Broken.

### ISSUE THREAD

**Issue by RowanHall** [opl-/beatsaber-http-status#11]
Added both the HTTP and WS DLLs to the /plugins/ folder.
Node and my browser could not acsess it at all.

Fiddler 4 Log:
`[Fiddler] The connection to 'localhost' failed. 
Error: ConnectionRefused (0x274d). 
System.Net.Sockets.SocketException No connection could be made because the target machine actively refused it 127.0.0.1:6557`

Am I doing something wrong?

**Comment by RowanHall** [comment]
The latest for each as of 3:31 PM 12/22/18

**Comment by opl-** [comment]
The current most recent version of the plugin is for Beat Saber 0.11, not 0.12. I will be releasing a new version for Beat Saber 0.12 some time this weekend, so you look out for that.

**Comment by opl-** [comment]
FYI, I just published the new version.
