### ISSUE TITLE
[Feature Request] Expose the song hash in the song start event

### ISSUE THREAD

**Issue by lolPants** [opl-/beatsaber-http-status#14]
This could be useful to pull additional data from BeatSaver using the 'search by hash' endpoint.

**Comment by opl-** [comment]
Would I need to integrate with some other plugin for this or can this be found in the vanilla game? Also, just to be clear, the song hash is actually in the format of `[0-9]+-[0-9]+`, right?

**Comment by lolPants** [comment]
```cs
string hash = LevelSO.levelID.Substring(0, Math.Min(32, LevelSO.levelID.Length));
```

**Comment by opl-** [comment]
Right, thanks. I will take a look at it when I can.
