### ISSUE TITLE
Hit Overlay 

### ISSUE THREAD

**Issue by ItsNovaHere** [opl-/beatsaber-http-status#15]
[I made an overlay](https://github.com/ItsNovaHere/hitoverlay) showing when notes are cut and where.  
Thanks for making this plugin and I hope to make more with it 👀  

[*Also an outdated video*](https://streamable.com/lgcdz), *don't question the song choice*

**Comment by opl-** [comment]
While I am questioning the song choice *and* the page title, that's a really cool thing you made! Added it to the wiki.

My suggestion for making the README file more user friendly: mention that it requires the plugin, give an example which modifies both query params, show an example of what the overlay does.
