### ISSUE TITLE
Add http-status to new beatmods repository

### ISSUE THREAD

**Issue by renssies** [opl-/beatsaber-http-status#20]
Since modsaber.org has been shut down a new repository has been created in the form of beatmods.com. 

However, http-status is still missing from that repository and might not be compatible yet with the new BSIPA and Beat Saber 0.13.2

**Comment by opl-** [comment]
Will look into it as soon as I can.

**Comment by opl-** [comment]
I submitted it to the repo. HTTP Status will be available on there as soon as it gets approved.
