### ISSUE TITLE
[Feature Request] Get beat saver song code?

### ISSUE THREAD

**Issue by Readie1593** [opl-/beatsaber-http-status#32]
Ive read through the source and I have no clue how it works so IDK if you could find a way to have the plugin get the current song code

**Comment by opl-** [comment]
I'm not sure if I could grab it easily without depending on Beat Saver and I can't really look into it right now. Might end up adding it at some point in the future, but for now no promises. PRs welcome.

**Comment by opl-** [comment]
ErisApps made a PR that finally correctly exposes the song hash for custom levels. This means that you can now use the <https://beatsaver.com/api/maps/by-hash/SONG_HASH> BeatSaver endpoint to retrieve information such as the song code and ratings from the BeatSaver API.

Hopefully this allows you to achieve your goal.
