### ISSUE TITLE
[Bug] Score not calculating properly

### ISSUE THREAD

**Issue by Zingabopp** [opl-/beatsaber-http-status#33]
Http-Status either isn't counting the hit (or multiplier increase) from the first note, or it's delaying it until the next note is hit. You can see in the video the combo is incremented, but the score remains at 0 after the first hit. After the 2nd hit, the score seems to be using the first hit's score. The gap gets worse as the song goes on, by the end there's a 2,080 point difference.
[Video](https://1drv.ms/v/s!Ao68s5T1f9xogeRjPcb7z22BHoIEiA?e=BWC2SF)

**Comment by opl-** [comment]
What version of the mod are you using? I believe #31 should have fixed this, but since the BeatMods staff still haven't accepted the v1.9.1 version you might still be using the unpatched version.

**Comment by opl-** [comment]
I should mention, as usual the v1.9.1 release is already on the [GitHub releases](https://github.com/opl-/beatsaber-http-status/releases) page, from the moment it was released.

**Comment by Zingabopp** [comment]
I was using the Beatmods version, it works fine on v1.91.
