### ISSUE TITLE
noteFullyCut finalScore not calculated correctly

### ISSUE THREAD

**Issue by hiinaspace** [opl-/beatsaber-http-status#34]
## Current behavior

the `.noteCut.FinalScore` in `noteFullyCut` events don't match the in-game final score, specifically the extra 15 points from cut precision. The maximum finalScore observed is 100, despite scores over 100 while in game. The `swingRating` field from the `noteCut` struct is also missing entirely, might be related.

FWIW, `.status.performance.lastNoteScore` is also always 0, on the same events.

## Expected behavior

`.finalScore` should match what's shown in the game's hit score indicators. `.swingRating` would be useful to have as well as `lastNoteScore`.

## Reproduction steps

1. Run beat saber with mod installed
2.  Run `websocat ws://127.0.0.1:6557/socket | jq --unbuffered 'select(.event=="NoteFullyCut") | .noteCut.finalScore' -r | tee -a scores.log` to see plugin output
3. Play song, observe scores from output don't match in-game score.

## Environment

BeatSaber version: 1.7.0
HTTP Status version: 1.9.1
Platform: SteamVR/Index

**Comment by opl-** [comment]
I'll try to look into this when I can. In the meantime tagging @Sarayalth and @ErisApps, who were both involved in updating the plugin to Beat Saber 1.7, in case either of them can fix it before me.

**Comment by JensSchadron** [comment]
I'll try to look into it somewhere this evening.

**Comment by ErisApps** [comment]
I'll try looking into it this evening when I've some time

**Comment by ErisApps** [comment]
@hiinaspace Hereby a really late answer, but I've spend some time today investigating the things you mentioned.
The SwingRating field can be brought back without issues as it's still saved in-memory, but simply isn't remapped onto the DTO.
About your other issue (the final score). I'm talking to @opl- about how it should be implemented, while trying to be comliant to the specs as stated in the protocol.md.

**Comment by ErisApps** [comment]
Both commits target the 2 specific issues mentioned in my previous message.
However, the issue regarding `.status.performance.lastNoteScore` isn't fixed yet.
