### ISSUE TITLE
Pass through songHash in StatusManager.cs

### ISSUE THREAD

**Issue by pogojonson** [opl-/beatsaber-http-status#39]
## Feature request
I need the songHash that is already present (Plugin.cs) being passed to the response beatmap json in StatusManager.cs.

## Motivation
I want to get the !bsr ID in my adaptation of the SongInfo Overlay by requesting a json response from https://beatsaver.com/api/maps/by-hash/$data.songHash .

A mockup is already working, all i need is the songHash by you guys :)

**Comment by opl-** [comment]
Pushed a potential fix to the `fix/songHash` branch. Build below. Please test and report if it fixes the issue.

[BeatSaberHTTPStatus-1.10.0-dev-bs1.8.0-6ebf5847.zip](https://github.com/opl-/beatsaber-http-status/files/4553434/BeatSaberHTTPStatus-1.10.0-dev-bs1.8.0-6ebf5847.zip)

**Comment by pogojonson** [comment]
I saw your discussion on the PR, with this early built it works for me, looking forward to the final build :)
