### ISSUE TITLE
Some maps contain unnecessary characters in songHash

### ISSUE THREAD

**Issue by rynan4818** [opl-/beatsaber-http-status#43]
## Current behavior

In some scores, the songHash and levelId of the beatmap contains unnecessary characters such as the song name.

Example.
https://beatsaver.com/beatmap/858

"songHash": "884E2D9A82F5675DE7C3FA35199EBF24C4F15D23_858 (citrus - mystikmol)",
"levelId": "custom_level_884E2D9A82F5675DE7C3FA35199EBF24C4F15D23_858 (citrus - mystikmol)",

I believe this is a higher level mod issue than the HTTPStatus issue.
However, I'm not sure what the problem is, to my ability, so I've reported it here.

I found this problem when I was trying to add the bsr display to beat-saber-overlay.
On the overlay side, I solved the problem by taking out only the first 40 characters.
https://github.com/Reselim/beat-saber-overlay/pull/15

I'm using a translation tool because I'm not very good at English.
Please note that there are some oddities in the text.
## Environment

BeatSaber version: 1.10.0
HTTP Status version: 1.11.0
Platform: (Vive, Oculus, other?) Vive pro

**Comment by rynan4818** [comment]
The cause has been found.
In the CustomLevels folder, there were two map data folders with the following identical contents
```
858 (citrus - kamome sano)
858 (citrus - mystikmol)
```
If there are multiple maps of the same songHash, the folder name will be added to the end of the levelID.

I think that levelId is good as it is, but songHash needs to be corrected.

**Comment by ErisApps** [comment]
Good catch @rynan4818, I tried the logic out on a metric ton of songs, but I wasn't aware of this happening to be honest. 😅
