### ISSUE TITLE
Songs stop loading after playing one song

### ISSUE THREAD

**Issue by yshui** [opl-/beatsaber-http-status#46]
## Reproduction steps

1. Start the game
2. Play one song to completion (with nothing using HTTP Status)
3. Return to menu
4. Select another song

## Current behavior

The other song won't load. The loading icon spins forever

## Environment

BeatSaber version: Tested with 1.8.0, 1.9.1, 1.10.0
HTTP Status version: 1.10.0
Platform: Vive, Linux with Proton 4.11

## Note

I only landed on HTTP Status through trial and error. I noticed this problem after updating to beat saber 1.10. I tried multiple things to troubleshot: downgrading the game, removing songs, removing plugins, etc. After removing HTTP Status, the problem seems to go away.

**Comment by yshui** [comment]
I don't understand how HTTP Status can cause this kind of problem. I should re-install HTTP Status and see if this comes back.

**Comment by yshui** [comment]
> I should re-install HTTP Status and see if this comes back.

it does...

**Comment by ShiroSFX** [comment]
Update to the lastest version 1.11.1 and look if that fixed (1.11.1 not in ModAssistant )

**Comment by opl-** [comment]
As ShiroSFX said, try updating to the 1.11.1 version which you can find on the [releases page](https://github.com/opl-/beatsaber-http-status/releases). If it still doesn't work, please include the logs ([instructions on how to get them here](https://bsmg.wiki/support/#understanding-logs)) so we can understand what's going wrong.

**Comment by yshui** [comment]
I'll try 1.11.1. But with 1.10.0, there is nothing interesting in the logs, no exceptions, etc.

**Comment by yshui** [comment]
1.11.1 has this problem too.

Some observations:

* doesn't have to play one song. let the game run long enough and this problem will occur
* this seems to have something to do with network access. same problem happens if i download songs with BeatSaverDownloader

**Comment by ErisApps** [comment]
Could you please still provide us with a logfile? We might be able to figure out something using it.

**Comment by yshui** [comment]
[log.gz](https://github.com/opl-/beatsaber-http-status/files/4836154/log.gz)

**Comment by opl-** [comment]
Looking at the list of mods you have installed and comparing it to Eris', it seems that most of them should work with HTTP Status. Something we can try doing is running the game with just HTTP Status installed to see if works. If it does, that means that one of the plugins is incompatible (possibly AlternativePlay?). If it doesn't, that means that it's indeed some issue with network access on Proton and we'll need to figure something out.

**Comment by opl-** [comment]
Closing issue due to lack of information. Comment to reopen.
