### ISSUE TITLE
Release a new version for Beat Saber v1.11.1

### ISSUE THREAD

**Issue by peddermaster2** [opl-/beatsaber-http-status#49]
The current code base seems to work with Beat Saber `v1.11.1`. I compiled it myself.

Should I create a PR with the updated game version number?

**Comment by untuned** [comment]
> The current code base seems to work with Beat Saber `v1.11.1`. I compiled it myself.
> 
> Should I create a PR with the updated game version number?

I would greatly appreciate this, could you also host the updated version somewhere so that I could download it?

**Comment by ErisApps** [comment]
There's nothing stopping you from using the latest version of this mod.
You'll only see a single warning that the mod wasn't originally created for BS 1.11.1 if you have the console open, but aside from that it works just fine.

**Comment by opl-** [comment]
Thanks for mentioning it. Eris mentioned some time ago that websocket-sharp (a dependency) hasn't been updated in a while, so I updated it in hopes of nothing breaking. Here's a [release candidate download](https://github.com/opl-/beatsaber-http-status/files/5144200/BeatSaberHTTPStatus-1.11.2-bs1.11.0-fe9e9d77.zip). If no one reports anything being broken in the next ~24 hours, I'll properly publish it.

**Comment by opl-** [comment]
No one reported any new issues, so I created a proper release here on GitHub and uploaded it to BeatMods (where it will be visible as soon as it's approved).
