### ISSUE TITLE
Add the ability to get the background color used

### ISSUE THREAD

**Issue by nmeurer** [opl-/beatsaber-http-status#56]
## Feature request
When playing the game, sometimes the *whole* background changes it's color (normaly from blue to red and vice versa). A request to get the background color change (and it's new color) would be really damn cool.

## Motivation
When hosting a beat saber party at home, for example, you could hook this up to some LED's or use a Wifi to DMX-Bridge for stage lights. I know, that there is a implementation for philips hue, but they only change the color according to a note being sliced and not to the background color being changed.

**Comment by LeoDJ** [comment]
Yes, I would be interested in this feature as well, why did you close your issue?

I noticed that lighting events alone don't contain every color change that happens. The changing background you mentioned is exactly what's missing as far as I can tell.
