### ISSUE TITLE
Wiki update for reslim's overlay

### ISSUE THREAD

**Issue by TheNoNinja** [opl-/beatsaber-http-status#58]
Now that https://github.com/Reselim/beat-saber-overlay isn't actively supported anymore I would like to add my personal fork to the wiki. It's an updated version of reslim's overlay. I have used if for my self for some time now but want to share it with other people now. Here is a link to the fork where I just committed all my changes https://github.com/TheNoNinja/beat-saber-overlay

**Comment by opl-** [comment]
Added it. I suggest you add an example showing the overlay with an actual song playing, since the current screenshot looks extremely bland compared to Reselim's, even though I know the two should look almost identical.

**Comment by TheNoNinja** [comment]
Yeah good call. Updated it.
Thanks for adding me ^-^
