### ISSUE TITLE
obstacleEnter and obstacleExit events not emited

### ISSUE THREAD

**Issue by SplitPixl** [opl-/beatsaber-http-status#6]
As of [this commit](https://github.com/opl-/beatsaber-http-status/commit/f22d7b25f8a70c58054d67647744d9717833c19a), obstacleEnter and obstacleExit events not emitted. In [this dump](https://gist.github.com/SplitPixl/e8aef0a7081bb5c6492d9d8097fdfe9f#file-beatsaber-websocket-1-dump-L167-L169), there should be `obstacleEnter `and `obstacleExit `events around lines 167 - 169.

**Comment by SplitPixl** [comment]
Something to note, this doesn't affect the current release.

**Comment by opl-** [comment]
Fixed by da4eb2b
