### ISSUE TITLE
"songStart" Event is not fired for certain Mod-Scores

### ISSUE THREAD

**Issue by Chickenbreadlp** [opl-/beatsaber-http-status#61]
## Current behavior
Certain mod-scores don't trigger the song start event.
It is possible that this is an issue with Noodle Extensions, as I've only encountered the issue with Maps using this mod, but not all Noodle Extension scores are broken in this way.
Pretty much all NE-maps I've tried with a Laweless Difficulty did not trigger the event, but if my memory serves me right, there was one more map in my collection that had the same behavior *without* having a Laweless difficulty.

## Expected behavior
Event songStart should be triggered for all songs when the user clicks on play.

## Reproduction steps

1. Install Noodle Extensions
2. Download a Noodle Extension map that has a Laweless Difficulty (ex. "Up & Down" mapped by "thegoodboi": https://bsaber.com/songs/11cf8/)
3. Observe the HTTP WebSocket
4. Play the map

## Environment

BeatSaber version: 1.14.0
HTTP Status version: 1.15.0 & 1.15.1
Platform: Index, Windows 10 20H2

**Comment by Chickenbreadlp** [comment]
Possibly related to #59

**Comment by opl-** [comment]
Please send a [game log](https://bsmg.wiki/support/#understanding-logs) from a session where this happened. I'm unfortunately still unable to launch the game so unless someone else takes this that's the best I can do here.

**Comment by Chickenbreadlp** [comment]
This *should* be the log where I tested 1.15.1 of BeatSaberHTTP for the other bug I had reported. I first tried a song where the Event triggered just fine, and then as a second song I tested "Up & Down", which as mentioned in the OP is broken regarding the Event.
[2021.04.18.20.12.51.log](https://github.com/opl-/beatsaber-http-status/files/6338718/2021.04.18.20.12.51.log)

**Comment by Chickenbreadlp** [comment]
Had some time yesterday to record a verbose log.
Here ya go: [2021.04.20.20.36.45.log](https://github.com/opl-/beatsaber-http-status/files/6347945/2021.04.20.20.36.45.log)

**Comment by opl-** [comment]
Here's a test build that should fix this issue (if my guess on which part is breaking is right): [BeatSaberHTTPStatus-1.15.1-dev-bs1.14.0-c005394e.zip](https://github.com/opl-/beatsaber-http-status/files/6563224/BeatSaberHTTPStatus-1.15.1-dev-bs1.14.0-c005394e.zip) (code in [fix/61](https://github.com/opl-/beatsaber-http-status/tree/fix/61)). Here's an alternate fix in case the previous one doesn't work: [BeatSaberHTTPStatus-1.15.1-dev-bs1.14.0-5015c408.zip](https://github.com/opl-/beatsaber-http-status/files/6563202/BeatSaberHTTPStatus-1.15.1-dev-bs1.14.0-5015c408.zip) (code in 5015c408).

I'm leaving the issue open as I'm not sure if this is the right way to fix this. I'd have to do practical testing to see how Noodle Extensions modifies the data.

**Comment by Chickenbreadlp** [comment]
I just tried the first Dev-Build you've attached (the one from Branch [fix/61](https://github.com/opl-/beatsaber-http-status/tree/fix/61)) and everything seems to be working fine. I've ran through a couple of songs (both NE and not with and without Lawless) and HTTP Status worked as intended.

Just in case I've attached another log file here: 
[2021.05.29.16.51.41.log](https://github.com/opl-/beatsaber-http-status/files/6564869/2021.05.29.16.51.41.log)
