### ISSUE TITLE
currentMaxScore is not updated when notes cut is missed.

### ISSUE THREAD

**Issue by rynan4818** [opl-/beatsaber-http-status#63]
## Current behavior
The currentMaxScore, which is required for calculating accuracy, is only updated in scoreChanged events.
If you miss a notes cut, there will be a difference between the accuracy displayed in the in-game UI and the accuracy displayed in the overlay.
If a miss is made at the end of the game, the game ends without updating the accuracy, causing problems when using the overlay display as a record.

## Expected behavior
I think it is necessary to update the currentMaxScore on noteMissed events as well, or at least send the data with updated currentMaxScore at the end of the game.

BeatSaber version: 1.15.0
HTTP Status version: 1.15.1

**Comment by opl-** [comment]
Looking at the code, it seems that this might also be a problem in the `noteCut` and `noteMissed` events. They both increment the `passedNotes` count without updating `currentMaxScore` afterwards. Is that indeed the case?

**Comment by rynan4818** [comment]
That's right.
I tried adding 'UpdateCurrentMaxScore()' to the next line after 'gameStatus.passedNotes++' in 'OnNoteWasMissed' and 'OnNoteWasCut', and it works as expected.
![image](https://user-images.githubusercontent.com/14249877/119262458-4b167f00-bc16-11eb-9bde-92e0467be43a.png)
The image checking tool is my own work and is available below.
https://rynan4818.github.io/http_status_check2.html
