### ISSUE TITLE
Menu event doesn't fire on the new release. 

### ISSUE THREAD

**Issue by Morichalion** [opl-/beatsaber-http-status#64]
## Current behavior

Menu event doesn't fire. 

## Expected behavior

Menu even should fire when leaving game to go to a menu. 

## Reproduction steps

1. Finish song or fail song. 
2. See behavior reliant on menu event not work. 

## Solution
1. Change overlay to use "finished" or "failed" events. 

BeatSaber version: 1.16.1
HTTP Status version:  1.16.1
Platform: Index. LIV.

**Comment by Morichalion** [comment]
To be clear, this just strikes me as a documentation issue. The menu event isn't really needed

**Comment by opl-** [comment]
Fixed in 23cdee6
