### ISSUE TITLE
Event ObstacleEnter/Exit not fired

### ISSUE THREAD

**Issue by ShiroSFX** [opl-/beatsaber-http-status#67]
Hello,

I don't know if you work for the 1.16.2 version, but Event ObstacleEnter & Exit don't work at this time :)

(I use these for calculate the HP bar so without them that a bit "not working")
(I cant reopen the old issue so, new one)

### Reproducing Step
I confirmed this by doing a console.log(event) directly and play fitbit map and go into walls.

### Environment
BeatSaber version: 1.16.2
HTTP Status version: lastest (1.16.1)
Platform: Steam BeatSaber with Index

**Comment by opl-** [comment]
I swear I checked that it works on BS 1.16.1 and that it worked. I even just double checked that my logs from then have it. Either they changed something in BS 1.16.2 or one of your mods is incompatible with your game. Could you send a log file created when  this issue happened to you?

**Comment by ShiroSFX** [comment]
Okay,

So i checked the log nothing wrong in.
But yea a mod has breaked this event, i use this mod because that awful to put my headset each time i does an edit a code line.
(MouseSaber but no updated for 1.16)

So without this that work fine, i should have know ...
