### ISSUE TITLE
A new clean Overlay :3

### ISSUE THREAD

**Issue by HyldraZolxy** [opl-/beatsaber-http-status#79]
Heyowwww !
I have created an overlay that uses HTTPStatus
I saw that i had to create a ticket to put it on the overlay page available for this plugin, so here it is :3

Here is a preview:
Top left
![InfoSong-inWorking](https://user-images.githubusercontent.com/48021253/140139153-e0af025b-8642-46a3-9099-aff8174ff22c.png)

Bottom left
![Performance-inWorking](https://user-images.githubusercontent.com/48021253/140139456-fbf655f8-30f5-4e07-85e6-4070c8ccbeed.png)

You can add my Github: https://github.com/HyldraZolxy/BeatSaber-Overlay
And add the link for use that overlay: https://overlay.hyldrazolxy.fr/

Thanks you ! ^-^

**Comment by opl-** [comment]
Added. :+1:
