### ISSUE TITLE
SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by nanikit** [opl-/beatsaber-http-status#81]
## Current behavior

Connecting to 127.0.0.1:6557/status.json results connection refused.

_latest.log contained the following.

```
[INFO @ 01:14:23 | Beat Saber HTTP Status] Starting HTTP server on port 6557
[ERROR @ 01:14:23 | IPA] Beat Saber HTTP Status OnEnable: System.InvalidOperationException: The underlying listener has failed to start. ---> System.Net.Sockets.SocketException: 액세스 권한에 의해 숨겨진 소켓에 액세스를 시도했습니다.
[ERROR @ 01:14:23 | IPA]   at System.Net.Sockets.Socket.Bind (System.Net.EndPoint localEP) [0x00043] in <ef151b6abb5d474cb2c1cb8906a8b5a4>:0 
[ERROR @ 01:14:23 | IPA]   at WebSocketSharp.Net.EndPointListener..ctor (System.Net.IPEndPoint endpoint, System.Boolean secure, System.String certificateFolderPath, WebSocketSharp.Net.ServerSslConfiguration sslConfig, System.Boolean reuseAddress) [0x000b6] in <7a2bdf4fe6004810ba771c682597b1d8>:0 
[ERROR @ 01:14:23 | IPA]   at WebSocketSharp.Net.EndPointManager.addPrefix (System.String uriPrefix, WebSocketSharp.Net.HttpListener listener) [0x00130] in <7a2bdf4fe6004810ba771c682597b1d8>:0 
[ERROR @ 01:14:23 | IPA]   at WebSocketSharp.Net.EndPointManager.AddListener (WebSocketSharp.Net.HttpListener listener) [0x00094] in <7a2bdf4fe6004810ba771c682597b1d8>:0 
[ERROR @ 01:14:23 | IPA]   at WebSocketSharp.Net.HttpListener.Start () [0x00016] in <7a2bdf4fe6004810ba771c682597b1d8>:0 
[ERROR @ 01:14:23 | IPA]   at WebSocketSharp.Server.HttpServer.startReceiving () [0x00002] in <7a2bdf4fe6004810ba771c682597b1d8>:0 
[ERROR @ 01:14:23 | IPA]    --- End of inner exception stack trace ---
[ERROR @ 01:14:23 | IPA]   at WebSocketSharp.Server.HttpServer.startReceiving () [0x00020] in <7a2bdf4fe6004810ba771c682597b1d8>:0 
[ERROR @ 01:14:23 | IPA]   at WebSocketSharp.Server.HttpServer.start () [0x000d3] in <7a2bdf4fe6004810ba771c682597b1d8>:0 
[ERROR @ 01:14:23 | IPA]   at WebSocketSharp.Server.HttpServer.Start () [0x00023] in <7a2bdf4fe6004810ba771c682597b1d8>:0 
[ERROR @ 01:14:23 | IPA]   at BeatSaberHTTPStatus.HTTPServer.InitServer () [0x00063] in <3d3adfc0a3df41e5bf686d95b6b4e046>:0 
[ERROR @ 01:14:23 | IPA]   at BeatSaberHTTPStatus.Plugin.OnApplicationStart () [0x00024] in <3d3adfc0a3df41e5bf686d95b6b4e046>:0 
[ERROR @ 01:14:23 | IPA]   at (wrapper dynamic-method) System.Object.lambda_method(System.Runtime.CompilerServices.Closure,object)
[ERROR @ 01:14:23 | IPA]   at IPA.Loader.PluginExecutor.Enable () [0x0000c] in <763a0cb55a5e418c81b67cf4601dddbb>:0 
[ERROR @ 01:14:23 | IPA]   at IPA.Loader.Composite.CompositeBSPlugin+<>c.<OnEnable>b__4_0 (IPA.Loader.PluginExecutor plugin) [0x00000] in <763a0cb55a5e418c81b67cf4601dddbb>:0 
[ERROR @ 01:14:23 | IPA]   at IPA.Loader.Composite.CompositeBSPlugin.Invoke (IPA.Loader.Composite.CompositeBSPlugin+CompositeCall callback, System.String method) [0x00018] in <763a0cb55a5e418c81b67cf4601dddbb>:0 
```

## Expected behavior
I should receive any json.

## Reproduction steps

1. Install this mod by ModAssistant.
2. Start beat saber.
3. Open http://127.0.0.1/status.json in Google Chrome.

## Environment
OS: Microsoft Windows 10 Pro 10.0.19043 N/A Build 19043
BeatSaber version: 1.18.1
HTTP Status version: 1.19.1
Platform: Oculus Quest 2

**Comment by opl-** [comment]
Please post the full game log. The issue title mentions an exception not listed in the log you attached.

**Comment by nanikit** [comment]
The title is unlocalized message by me. That's `액세스 권한에 의해 숨겨진 소켓에 액세스를 시도했습니다.`.
I attach the full log anyway.
[2021.11.12.04.54.38.zip](https://github.com/opl-/beatsaber-http-status/files/7529095/2021.11.12.04.54.38.zip)

**Comment by opl-** [comment]
Yeah, I looked up a translation, but thought you might've forgotten to include some exception due to the additional error code in the title and reproduction steps listing `/status.json`. It seems the log doesn't contain any other relevant information but better safe than sorry. Thank you for including it.

The exception happens on initialization, meaning that the HTTP server never starts up. In fact, it happens when trying to tell the system "hey, I want to receive connections on port 6557".

The first thing I'd check is if you don't happen to have another program taking up port 6557.

Open a console in administrator mode and type in `netstat -ab`[1]. This should list which ports which programs are listening on. Check if there are any list entries showing `TCP <ip>:6557`. If there are, you have another program already listening on that port.

---

The 10013 error code seems to be `WSAEACCES`, documented as[2]:

> Permission denied.
    An attempt was made to access a socket in a way forbidden by its access permissions. An example is using a broadcast address for sendto without broadcast permission being set using setsockopt(SO_BROADCAST).
    Another possible reason for the WSAEACCES error is that when the bind function is called (on Windows NT 4.0 with SP4 and later), another application, service, or kernel mode driver is bound to the same address with exclusive access. Such exclusive access is a new feature of Windows NT 4.0 with SP4 and later, and is implemented by using the SO_EXCLUSIVEADDRUSE option.

[1] https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/netstat
[2] https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2

**Comment by nanikit** [comment]
I already resolved this issue by [this](https://superuser.com/a/1610009). At that time I checked netstat, but no process use that port. It is not important maybe, the fact that some process reserved that port won't change.

I shared this because I thought it might happen to other people too. If you think no action is required, feel free to close this.

**Comment by opl-** [comment]
Glad you were capable of solving this yourself, because I didn't have many other ideas beyond "port might be already in use". Thanks for sharing the solution. You learn something every day.
