### ISSUE TITLE
Add beatmap characteristic

### ISSUE THREAD

**Issue by peddermaster2** [opl-/beatsaber-http-status#84]
## Feature request

It would be helpful to get selected beatmap characteristic where we have the difficulty.

## Motivation

This is helpful for displaying if it is not "Standard", e.g. "Lawless".

I also use it to log the result of the played beatmap to a local database for analysis. And for levels with multiple characteristics it is currently impossible to know which one was selected.

**Comment by peddermaster2** [comment]
I have made a try in https://github.com/peddermaster2/beatsaber-http-status/tree/add-characteristic .  
Should I create a PR?

**Comment by peddermaster2** [comment]
@opl- I have also noticed while coding this, that the map characteristic are encoded in the "mode" field. The documentation lists the possible values but all combinations with `Lightshow` and `Lawless` are missing.

**Comment by opl-** [comment]
Indeed, this is already part of `game.mode`. As a comment in the code states, `// This was an awful idea.` It exists for historical purposes, as back in Beat Saber 0.11.1 that's the string the game had in the setup data ([link to line in 1.0.0](https://github.com/opl-/beatsaber-http-status/commit/6f23b26aa0b64eaf31bd8c0dacde1145a1ae7110#diff-88fc228e047562c56fe97c434d848432ca74b48ddc5cd1c5b266613c0073e12bR159)).

Lightshow and Lawless can both still appear in there, as can 90/360. The documentation just hasn't been updated to include them.

I think the best solution here is to add `beatmap.characteristic` as per your suggestion (linking to BSMG wiki in protocol.md for current list of characteristics), and update the documentation to explain that `game.mode` starts with the current mode followed by the characteristic, and that if the characteristic is wanted `beatmap.characteristic` should be used instead.

This keeps backwards compatibility, allows people to easily find out what the mode is by checking the beginning of the string (or getting a substring using length of `beatmap.characteristic` if exact value is *really* needed), and of course makes the characteristic trivial to retrieve. I don't think anyone has much of a use for the mode (solo/party/multiplayer) anyway, other than knowing if it's multiplayer or not.

If no one has any objections I'll implement these changes over the weekend.

**Comment by opl-** [comment]
So, that was a very long weekend... Won't get published until #82 either gets fixed or tires me out.
